import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossOrigin="anonymous"/>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="row pt-1">
          <div className="col-2 border border-primary text-center">
            LOGO
          </div>
          <div className="col border border-primary text-center">
              <Link href = "/lab_20" className="m-5">Lab_20</Link>
              <Link href = "/lab_21" className="m-5">Lab_21</Link>
              <Link href = "/lab_22"className="m-5">Lab_22</Link>
              <Link href = "/lab_23"className="m-5">Lab_23</Link>
              <Link href = "/lab_24"className="m-5">Lab_24</Link>
          </div>
        </div>
        <div className="row">
          <div className="col-2 border border-primary text-center">
            SIDEBAR
          </div>
          <div className="col border border-primary text-center">
            {children}
          </div>
        </div>
        <div className="row">
          <div className="col border border-primary text-center">
            FOOTER
          </div>
        </div>
      </body>
    </html>
  );
}
