import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <nav className='pt-5 pb-5'>
                <Link href = "/lab_20/contact" className='m-5'>contact</Link>
                <Link href = "/lab_20/about" className='m-5'>About</Link>
                <Link href = "/lab_20/detail" className='m-5'>Detail</Link>
            </nav>
        {children}
      </body>
    </html>
  );
}
